import Header from "../components/header";
import Footer from "../components/footer";
import { Expletus_Sans } from "next/font/google";
import "./globals.css";

const expletusSans = Expletus_Sans({
  variable: "--expletusSans-font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${expletusSans.variable}`}>
      <body>
        <div className="h-full bg-[url('/photography-bg.jpeg')] bg-top bg-cover overflow-auto">
          <Header />
          {/* <CategoryMenu /> */}
          <main className="pt-[110px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
