import Header from "../components/header";
import Footer from "../components/footer";
import CategoryMenu from "../components/CategoryMenu";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-full bg-[url('/photography-bg.jpeg')] bg-top bg-cover">
          <Header />
          {/* <CategoryMenu /> */}
          <main className="grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
